import type { Study, Insight, Participant, ThemeCluster, ProductImpact } from './types';

export const studies: Study[] = [
  {
    id: '1',
    title: 'Onboarding Flow Usability',
    status: 'in-progress',
    type: 'usability',
    owner: 'Sarah Chen',
    ownerAvatar: 'SC',
    participants: { target: 12, current: 8 },
    dueDate: '2026-02-15',
    tags: ['onboarding', 'new-users', 'mobile'],
    priority: 'high',
  },
  {
    id: '2',
    title: 'Enterprise Feature Discovery',
    status: 'recruiting',
    type: 'interview',
    owner: 'Marcus Johnson',
    ownerAvatar: 'MJ',
    participants: { target: 15, current: 3 },
    dueDate: '2026-02-28',
    tags: ['enterprise', 'features', 'discovery'],
    priority: 'high',
  },
  {
    id: '3',
    title: 'Dashboard Redesign Validation',
    status: 'analysis',
    type: 'usability',
    owner: 'Elena Rodriguez',
    ownerAvatar: 'ER',
    participants: { target: 10, current: 10 },
    dueDate: '2026-02-05',
    tags: ['dashboard', 'redesign', 'power-users'],
    priority: 'medium',
  },
  {
    id: '4',
    title: 'Pricing Page A/B Test',
    status: 'completed',
    type: 'a-b-test',
    owner: 'David Kim',
    ownerAvatar: 'DK',
    participants: { target: 500, current: 524 },
    dueDate: '2026-01-20',
    tags: ['pricing', 'conversion', 'growth'],
    priority: 'high',
  },
  {
    id: '5',
    title: 'Weekly User Diary Study',
    status: 'in-progress',
    type: 'diary',
    owner: 'Sarah Chen',
    ownerAvatar: 'SC',
    participants: { target: 20, current: 18 },
    dueDate: '2026-03-01',
    tags: ['habits', 'longitudinal', 'engagement'],
    priority: 'medium',
  },
  {
    id: '6',
    title: 'Navigation Card Sort',
    status: 'planning',
    type: 'card-sort',
    owner: 'Marcus Johnson',
    ownerAvatar: 'MJ',
    participants: { target: 30, current: 0 },
    dueDate: '2026-02-20',
    tags: ['navigation', 'ia', 'structure'],
    priority: 'low',
  },
  {
    id: '7',
    title: 'Checkout Flow Survey',
    status: 'blocked',
    type: 'survey',
    owner: 'Elena Rodriguez',
    ownerAvatar: 'ER',
    participants: { target: 200, current: 45 },
    dueDate: '2026-02-10',
    tags: ['checkout', 'conversion', 'friction'],
    priority: 'high',
  },
];

export const insights: Insight[] = [
  {
    id: '1',
    title: 'Users struggle with multi-step forms on mobile',
    summary: 'Participants consistently expressed frustration when completing forms with more than 3 steps on mobile devices. Key pain points include losing progress and unclear navigation between steps.',
    studyId: '1',
    studyName: 'Onboarding Flow Usability',
    confidence: 'high',
    impact: 'high',
    themes: ['mobile-ux', 'forms', 'friction'],
    createdAt: '2026-01-28',
    createdBy: 'Sarah Chen',
    createdByAvatar: 'SC',
    linkedProducts: ['Mobile App', 'Web App'],
    evidenceCount: 12,
  },
  {
    id: '2',
    title: 'Enterprise users need bulk actions for team management',
    summary: 'Interview participants from large organizations (500+ employees) need to manage team permissions in bulk. Current one-by-one approach is time-prohibitive.',
    studyId: '2',
    studyName: 'Enterprise Feature Discovery',
    confidence: 'high',
    impact: 'high',
    themes: ['enterprise', 'permissions', 'efficiency'],
    createdAt: '2026-01-25',
    createdBy: 'Marcus Johnson',
    createdByAvatar: 'MJ',
    linkedProducts: ['Admin Portal'],
    evidenceCount: 8,
  },
  {
    id: '3',
    title: 'Dashboard information density overwhelms new users',
    summary: 'New users (< 30 days) feel overwhelmed by the amount of data presented on the main dashboard. They prefer guided views that progressively reveal complexity.',
    studyId: '3',
    studyName: 'Dashboard Redesign Validation',
    confidence: 'medium',
    impact: 'medium',
    themes: ['onboarding', 'dashboard', 'complexity'],
    createdAt: '2026-01-22',
    createdBy: 'Elena Rodriguez',
    createdByAvatar: 'ER',
    linkedProducts: ['Web App'],
    evidenceCount: 10,
  },
  {
    id: '4',
    title: 'Pricing tier names create confusion',
    summary: 'Variant B with descriptive tier names (Starter, Growth, Enterprise) outperformed variant A (Basic, Pro, Ultimate) by 23% in conversion rate.',
    studyId: '4',
    studyName: 'Pricing Page A/B Test',
    confidence: 'high',
    impact: 'high',
    themes: ['pricing', 'naming', 'conversion'],
    createdAt: '2026-01-20',
    createdBy: 'David Kim',
    createdByAvatar: 'DK',
    linkedProducts: ['Marketing Site'],
    evidenceCount: 524,
  },
  {
    id: '5',
    title: 'Power users want keyboard shortcuts',
    summary: 'Heavy users (> 4 hours daily) consistently request keyboard shortcuts for common actions. Top requested: navigation, search, and quick actions.',
    studyId: '3',
    studyName: 'Dashboard Redesign Validation',
    confidence: 'high',
    impact: 'medium',
    themes: ['power-users', 'efficiency', 'shortcuts'],
    createdAt: '2026-01-18',
    createdBy: 'Elena Rodriguez',
    createdByAvatar: 'ER',
    linkedProducts: ['Web App'],
    evidenceCount: 7,
  },
];

export const participants: Participant[] = [
  {
    id: '1',
    name: 'Alex Thompson',
    email: 'alex.t@example.com',
    avatar: 'AT',
    segment: 'Power User',
    studiesParticipated: 8,
    lastActivity: '2026-01-30',
    status: 'active',
    tags: ['enterprise', 'desktop', 'frequent'],
  },
  {
    id: '2',
    name: 'Maria Garcia',
    email: 'maria.g@example.com',
    avatar: 'MG',
    segment: 'New User',
    studiesParticipated: 2,
    lastActivity: '2026-01-28',
    status: 'active',
    tags: ['startup', 'mobile', 'new'],
  },
  {
    id: '3',
    name: 'James Wilson',
    email: 'james.w@example.com',
    avatar: 'JW',
    segment: 'Enterprise Admin',
    studiesParticipated: 5,
    lastActivity: '2026-01-25',
    status: 'active',
    tags: ['enterprise', 'admin', 'decision-maker'],
  },
  {
    id: '4',
    name: 'Sophie Lee',
    email: 'sophie.l@example.com',
    avatar: 'SL',
    segment: 'SMB Owner',
    studiesParticipated: 3,
    lastActivity: '2026-01-20',
    status: 'pending',
    tags: ['smb', 'owner', 'mobile'],
  },
  {
    id: '5',
    name: 'Ryan Patel',
    email: 'ryan.p@example.com',
    avatar: 'RP',
    segment: 'Developer',
    studiesParticipated: 6,
    lastActivity: '2026-01-15',
    status: 'inactive',
    tags: ['technical', 'api-user', 'integrations'],
  },
];

export const themesClusters: ThemeCluster[] = [
  { name: 'Mobile Experience', count: 24, percentage: 28, trend: 'up' },
  { name: 'Enterprise Features', count: 18, percentage: 21, trend: 'up' },
  { name: 'Onboarding', count: 15, percentage: 18, trend: 'stable' },
  { name: 'Performance', count: 12, percentage: 14, trend: 'down' },
  { name: 'Pricing & Plans', count: 10, percentage: 12, trend: 'up' },
  { name: 'Integrations', count: 6, percentage: 7, trend: 'stable' },
];

export const productImpacts: ProductImpact[] = [
  { metric: 'Conversion Rate', value: '+23%', change: 23, linkedInsights: 3 },
  { metric: 'User Activation', value: '+15%', change: 15, linkedInsights: 5 },
  { metric: 'Support Tickets', value: '-32%', change: -32, linkedInsights: 4 },
  { metric: 'Feature Adoption', value: '+41%', change: 41, linkedInsights: 2 },
  { metric: 'NPS Score', value: '+12pts', change: 12, linkedInsights: 6 },
];

export const overviewMetrics = {
  insightsShipped: { '7d': 8, '30d': 32, '90d': 87 },
  studiesInProgress: 3,
  studiesBlocked: 1,
  studiesCompleted: 12,
  avgConfidence: 78,
  participantPoolSize: 284,
  researchRequests: { pending: 5, inSla: 4, backlog: 8 },
};
